---
repos:
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
    # Update the sha variable with the release version that you want, from the yamllint repo
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.15.0
      hooks:
          - id: yamllint
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.1.0
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.15
      hooks:
          - id: isort
